---
title: "Contribution0"
description: |
  How to manage the page you are in charge of
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file.path("R", "functions.R"))
```


If you are in charge of a page, you should appear in the first section of this document and should have been granted with access to the source code. If not, please send an email to floriane.c.plard@gmail.com.

# Organisation of the website

## site plan


### Basics

##### [R](basics_r.html): Vincent Miele?

*contribute: I think there is already enough online on basic stuff but we need more advanced resources about coding*

##### [Ethics](basics_ethics.html): **Sandra Hamel**

*contribute: V Amrhein, A Gelman, S Nakagawa ([Founding Members of Sortee](https://www.sortee.org/people/)), *

##### [Data](basics_data.html): 
*contribute: already a lot of things to add from the web*


##### [Stats](basics_stats.html): **Gilles Yoccoz**

##### [Maths](basics_maths.html): **Fred Barraquand**

*contribute: J Matthiopoulos, B McGill, S Otto, F Débarre, Lyon teachers?, [M Bonsall](https://www.zoo.ox.ac.uk/people/professor-michael-bonsall?filter_types-1860401[]=&filter_series-1860401[]=#tab-1860396)*

There are things online but I did not find really ecologist friendly courses so far. 


### Modeling

##### [Regression](modeling_regression.html): **Gilles Yoccoz**

 *contribute: RA Poldrack, Mickael Clark, William A Link, [Peter Adler](https://qcnr.usu.edu/directory/adler_peter), B Bolker, M Brooks, JD Hadfield, L Crespin, D Westneat, G Simpson, B Shipley, J Lefcheck, PB Conn, M Hooten, N T Hobbs, C Dormann, F Hartig*


##### [Bayesian Approach](modeling_bayesian.html): **Olivier Gimenez**

*contribute: R McElreath, F. Korner, P deValpine, T Hobbs*

Already some very good courses in this part and a lot of resources that can be indexed in the more specific folders from these courses & the web.


##### [Multivariate Analyses](modeling_multivariate.html): **Stéphane Dray**

*contribute: S Jadhav, M Palmer, F Husson, AB Dufour, J Thioulouse, P Legendre, P Peres-Neto, M Anderson, S Holmes, C ter Braak *


##### [Machine Learning](modeling_machinelearning.html): 

*contribute: JL Parouty, L Jacob? *
   
   wrote a book: *Grant Humphries, Dawn R. Magness, Falk Huettmann, Pablo Casas* 

   wrote scientific articles as first or last author about application in Ecology: *[Tim C D Lucas](https://timcdlucas.github.io/), André C Ferreira, Sylvain Christin, Nicolas Lecomte, Marek Borowiec, Alexander E white, Michael A Tabak, Ryan S. Miller*
 
   wrote blog about deep learning for Ecology: *Patrick Gray, [J Lefneck](https://jonlefcheck.net/)*



### byField

##### [Demography](byfield_demography.html): **Sarah Cubaynes**

*contribute: M Gamelon, C Bonenfant, S Bouwhuis, O Jones, [E. Matechou](https://www.kent.ac.uk/mathematics-statistics-actuarial-science/people/1039/matechou-eleni), F. colchero, R Chandler, M Schaub, G Péron, B Morgan, RS McCrea, D Fletcher, J Rotella*


##### [Population Dynamics](byfield_population.html): **Olivier Gimenez**

*contribute: C Nater, E Simmonds, [Evan Cooch](http://canuck.dnr.cornell.edu/teaching/), H Caswell, Y Vindenes, S Engen, A Lee, V Grotan, B O'Hara, D Koons, BE Saether, T Coulson, S Ellner, D Childs, M Schaub, T Besbeas, E Zipkin, V Radchuk, A. Kuparinen,  M Paniw, C Coste, P Klepac, CJ Metcalf, A de Roos, T van Dooren*


##### [Spatial Analyses](byfield_spatial.html): 

*contribute: G Péron, CJ Brown, A Royle, M Kéry, E Zipkin, B Gardner, J Lahoz-Monfort, [J Fieberg](https://fieberg-lab.cfans.umn.edu/people/john-fieberg), R Kays, R. [Langrock](https://www.uni-bielefeld.de/fakultaeten/wirtschaftswissenschaften/lehrbereiche/stats/team/prof.-dr.-roland-langrock/), B McClintock, N Ranc*


##### [Community Analyses](byfield_community.html): D Zeleny ? 
*contribute: D Borcard, F Gillet, D Zelený, G Blanchet, J Oksanen, GL Simpson, D. Roberts, Otso Ovoskainen, Francis Hui, David Warton*

#####  Cross-species Analysis:

*contribute: JF Lemaitre, S Nakagawa, V Ronget*
Meta-Analysis, Allometric models, Phylogeny


#####  [Quantitative Genetics](byfield_quantgenetics.html): **Pierre de Villemereuil**  ?

*contribute: LM Chevin, A Kuparinen, B Walsh, M Morrissey, T Bonnet*

Already [courses](https://www.youtube.com/watch?v=U-MTfNw7IvM) from B Walsh that can be added


##### Network Analysis: 

*contribute: *


