---
title: "Data manipulation and visualization"
description: |
  Resources to learn and improve data manipulation, exploration and visualization in R.
  
  maintained by : *Volunteer wanted* [Click [here to contribute](forms.html)]{style="float:right"}
date: "`r Sys.Date()`"
output: distill::distill_article
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```
###### **Icon Legend**:
**Type**:
course `r ilink("course", "")`
video `r ilink("video", "")`
exo `r ilink("exo", "")`
open book `r ilink("tuto", "")`
book `r ilink("book", "")`
article `r ilink("article", "")`
git repo `r ilink("github", "")`
website `r ilink("site", "")`
**level**: 
begin `r ilink("tuto", "", lvl=1)` intermediate `r ilink("tuto", "", lvl=2)` advanced `r ilink("tuto", "", lvl=3)`



## Data Science

Global resources to start data science including introductory and intermediate material on data manipulation, exploration, visualization and analysis.

| Name                                      | Links |
|-------------------------------------------|-------|
|**STAT 545** *J Bryan* -- A course about data wrangling, exploration, and analysis with R|`r ilink("tuto", "https://stat545.com/", lvl=1)`|
|**R for Data Science** *H Wickham, G Grolemund* Introduction to data science: import, transform, visualize and model data with literate programming and reproducible research  |`r ilink("tuto", "https://r4ds.had.co.nz/", lvl=1)` `r ilink("exo", "https://jrnold.github.io/r4ds-exercise-solutions/", lvl=1)`|
|**ModernDive** *C Ismay, A Y Kim* -- A textbook about statistical inference via data science|`r ilink("tuto", "https://moderndive.com/foreword.html", lvl=1)`|
|**Introduction to Data Science** *R A Irizarry* -- A textbook from R basics to an introduction to machine learning, through data manipulation and statistics in R|`r ilink("tuto", "https://rafalab.github.io/dsbook/", lvl=1)`|
|**R Programming 101** -- A youtube channel about data cleaning, manipulation & visualization |`r ilink("video", "https://www.youtube.com/c/RProgramming101/videos", lvl=1)`|
|**Exploratory Data Analysis** *J Helveston* -- A course to learn how to import, manipulate, clean, explore, visualize, and export data in R |`r ilink("course", "https://eda.seas.gwu.edu/", lvl=2)`|


## Data Manipulation
| Name                                      | Links |
|-------------------------------------------|-------|
|**Data Wrangling with R and the Tidyverse** *G. Grolemund* -- An introductory playlist  |`r ilink("video", "https://www.youtube.com/playlist?list=PL9HYL-VRX0oQOWAFoKHFQAsWAI3ImbNPk", lvl=1)`|
|**Cleaning ecological survey data for conservation scientists** *C J Brown, C Buelow* |`r ilink("tuto", "http://www.seascapemodels.org/RLS-data-prep-course/", lvl=1)`|
|**dplyr** *R Programming - DDS* -- an introductory playlist to dplyr and its functions|`r ilink("video", "https://www.youtube.com/watch?v=rm0BQSWoJlc&list=PLyogaPCPr32W9wbszOANRJiAvUbbymcCS", lvl=1)`|


### Tidyverse


| Name                                      | Links |
|-------------------------------------------|-------|
|**Introduction to the Tidyverse** *datacamp* -- Introduction to R and Tidyverse  |`r ilink("course", "https://www.datacamp.com/courses/introduction-to-the-tidyverse?utm_source=adwords_ppc&utm_medium=cpc&utm_campaignid=897699256&utm_adgroupid=47591961031&utm_device=c&utm_keyword=tidyverse&utm_matchtype=p&utm_network=g&utm_adpostion=&utm_creative=340731356356&utm_targetid=aud-517318242147:kwd-642175809013&utm_loc_interest_ms=&utm_loc_physical_ms=9000264&gclid=CjwKCAjwquWVBhBrEiwAt1KmwtG0cQsVll7o1lISih-Gbgyzgm3qRoYZhg2ZZWjn7t-dPpMnlFRCtxoCdTYQAvD_BwE", lvl=1)`|
|**Tidy Modeling with R** *M Kuhn, J Silge* -- Introduction to how to use Tidyverse  |`r ilink("tuto", "https://www.tmwr.org/", lvl=2)`|
|**Tidyverse style guide** *Hadley Wickham* -- Style used with Tidyverse  |`r ilink("tuto", "https://style.tidyverse.org/index.html", lvl=1)`|

## Data Visualization
| Name                                      | Links |
|-------------------------------------------|-------|
|**Fundamentals of Data Visualization** *C . Wilke* -- Theory on how to make right and nice figures, not R focused|`r ilink("tuto", "https://clauswilke.com/dataviz/", lvl=1)`|
|**R Graphics Cookbook** *W. Chang* -- A practical guide to help you generate high-quality graphs|`r ilink("tuto", "https://r-graphics.org/", lvl=1)`|
|**R for Ecologists** -- a youtube channel including basics on R and visualization |`r ilink("video", "https://www.youtube.com/c/RforEcologists/videos", lvl=1)`|
|**ggplot2** *H. Wickham* -- focus on explaining the grammar of graphics that ggplot2 uses, it is not a cookbook|`r ilink("tuto", "https://ggplot2-book.org/index.html", lvl=2)`|
|**Visualization** -- a R studio youtube playlist  |`r ilink("video", "https://www.youtube.com/playlist?list=PL9HYL-VRX0oQlhD34UPQq0nCR1k1-NjwE")`|



### Shiny

| Name                                      | Links |
|-------------------------------------------|-------|
|**Shiny gallery** -- Find ideas about what is possible to do |`r ilink("site", "https://shiny.rstudio.com/gallery/")`|
|**A shiny workshop to start** *D Valle and others* -- A full course to start with shiny |`r ilink("course", "https://lsw5077.github.io/shiny_workshop/", lvl=1)`|
|**Mastering Shiny** *Hadley Wickham* --  Designed to take you from knowing nothing about Shiny to being an expert developer|`r ilink("tuto", "https://mastering-shiny.org/", lvl=2)`|
|**Engineering Production-Grade Shiny Apps** *C Fay, S Rochette, V Guyader, C Girard* -- learn the process of building an application that will later be sent to production  |`r ilink("tuto", "https://engineering-shiny.org/index.html", lvl=2)`|
|**Shiny Developer Series** -- a youtube channel  |`r ilink("video", "https://www.youtube.com/c/ShinyDeveloperSeries/videos", lvl=2)`|






