---
title: "R"
description: |
  Resources to start programming and statistics with R
        
  maintained by : *Volunteer Wanted* [Click [here to contribute](forms.html)]{style="float:right"}

date: "`r Sys.Date()`"
output: distill::distill_article
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```

###### **Icon Legend**:
**Type**:
full course `r ilink("course", "")`
video `r ilink("video", "")`
exo `r ilink("exo", "")`
open book, tutorial, manual `r ilink("tuto", "")`
book (not free) `r ilink("book", "")`
article`r ilink("article", "")`
website`r ilink("site", "")`

**level**: begin `r ilink("tuto", "", lvl=1)` intermediate `r ilink("tuto", "", lvl=2)` advanced `r ilink("tuto", "", lvl=3)`

### Programming in R

| Name                                      | Links |
|-------------------------------------------|-------|
|**First steps in R** *Institut Pasteur & USR 3756* -- A very basic tutorial to start R |`r ilink("tuto", "https://hub-courses.pages.pasteur.fr/R_pasteur_phd/First_steps_RStudio.html", lvl=1)`|
|**Hands-On Programming with R** *G Grolemund* -- A practical guide to start programming with R|`r ilink("tuto", "https://rstudio-education.github.io/hopr/",lvl=1)`|
|**Introduction to Programming with R** *R Stauffer et al.* -- Basics R, writing, coding & manipulating data |`r ilink("tuto", "https://discdown.org/rprogramming/index.html", lvl=1)`|
|**Intro to Programming for Analytics** *J Helveston* -- Basics in R, include an introduction to Python |`r ilink("course", "https://p4a.seas.gwu.edu/",lvl=1)`|
|**R introduction** *J Mathys VIB* -- A simple tutorial to start with R, only|`r ilink("tuto", "https://material.bits.vib.be/topics/R/", lvl=1)`|
|**How to R** -- A youtube channel incuding short videos on basics R, data manipulation and visualization|`r ilink("video", "https://www.youtube.com/c/HowToR4U/videos", lvl=1)`|
|**Advanced R** *H Wickham* --|`r ilink("tuto","http://adv-r.had.co.nz/",lvl=2)`|
|**Efficient R programming** *C Gillespie R Lovelace* -- Increase the amount of work you can do with R in a given amount of time|`r ilink("tuto", "https://csgillespie.github.io/efficientR/", lvl=2)`|
|**Avoid for loops** *R programming DDS* -- Learn how to make your code faster|`r ilink("video", "https://www.youtube.com/watch?v=dhfM4xeHVHI&list=PLyogaPCPr32UaTp-9Fsj4tb_aIcAQ3jKb", lvl=2)`|


### Data science in R

| Name                                      | Links |
|-------------------------------------------|-------|
|**Statistics and Data Science with R** *M Marin* -- A complete course to start statistics with R. 5 series: getting started, descriptive statistics, probability distribution, bivariate analysis, linear regression with R|`r ilink("course", "https://www.statslectures.com/r-stats-videos-tutorials",lvl=1)`|
|**Introduction to Data Science** *R A Irizarry* -- A complete guide including R basics, data wrangling, data visualisation, statistics and machine learning|`r ilink("tuto", "https://rafalab.github.io/dsbook/",lvl=1)`|
|**R Programming for Data Science** *R D Peng* -- Start with R, load and manipulate your data  |`r ilink("tuto", "https://bookdown.org/rdpeng/rprogdatascience/", lvl=1)`|
|**Learning statistics with R** *D Navarro* -- A tutorial for beginners to start statistics and simple tests with R|`r ilink("tuto", "https://learningstatisticswithr.com/book/", lvl=1)`|
|**Applied Quantitative Methods** *D McGlinn* -- A more advanced course introducing R programming, version control, SQL, GIS, spatial statistics, multivariate statistics|`r ilink("course", "https://dmcglinn.github.io/quant_methods/lessons/", lvl=2)`|


### Packages
| Name                                      | Links |
|-------------------------------------------|-------|
|**R Packages** *H Wickham, J Bryan* |`r ilink("tuto", "https://r-pkgs.org/index.html", lvl=2)`|


### Others

| Name                                      | Links |
|-------------------------------------------|-------|
|**R studio cheatsheets** -- Very useful synthetic sheets to find the function you need|`r ilink("site", "https://www.rstudio.com/resources/cheatsheets/")`|
|**Rstudio youtube channel** |`r ilink("video", "https://www.youtube.com/c/RStudioPBC/playlists")`|
|**R Reference Card** -- Quick access & definition to simple R functions|`r ilink("tuto", "https://cran.r-project.org/doc/contrib/Short-refcard.pdf")`|
|**R-Uni** -- A list of R tutorials and resources in university webpages|`r ilink("site", "https://pairach.com/2012/02/26/r-tutorials-from-universities-around-the-world/")`|




