---
title: "Ethical Statistics"
description: |
  Resources for reproducible and ethical statistics.
        
  maintained by : **Sandra Hamel** [Click [here to contribute](forms.html)]{style="float:right"}

date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```
###### **Icon Legend**:
**Type**:
course `r ilink("course", "")`
video `r ilink("video", "")`
exo `r ilink("exo", "")`
open book `r ilink("tuto", "")`
book `r ilink("book", "")`
article `r ilink("article", "")`
git repo `r ilink("github", "")`
website `r ilink("site", "")`

**level**: 
begin `r ilink("tuto", "", lvl=1)` intermediate `r ilink("tuto", "", lvl=2)` advanced `r ilink("tuto", "", lvl=3)`



## Reproducibility & replicability


| Name                                      | Links |
|-------------------------------------------|-------|
|**Reproducible science workshop** *O Gimenez* -- A full overview to start making your analyses reproducible |`r ilink("course", "https://oliviergimenez.github.io/reproducible-science-workshop/", lvl=1)`|
|**A better approach for dealing with reproducibility and replicability in science** *JD Nichols et al.* -- An opinion paper to emphasise the need for replicability in addition to reproducibility |`r ilink("article", "https://www.pnas.org/doi/10.1073/pnas.2100769118", lvl=1)`|
|**A Beginner's Guide to Conducting Reproducible Research** *JM Alston & JA Rick* -- Describe why we should and and how we can conduct reproducible research |`r ilink("article", "https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/bes2.1801", lvl=1)`|
|**Comments on reproducibility** *K Broman* -- Some do's and don'ts for improving reproducibility when using R Markdown|`r ilink("site", "https://kbroman.org/knitr_knutshell/pages/reproducible.html", lvl=2)`|
|**Computational notebooks** *L Figueiredo, C Scherer, A T Navarro* -- A simple kit to use computational notebooks|`r ilink("github", "https://github.com/FellowsFreiesWissen/computational_notebooks", lvl=2)`|
|**Jupyterhub** -- Interactive environment for notebooks, code, and data|`r ilink("site", "https://jupyter.org/hub", lvl=1)`|
|**Best practices for accessible and reproducible code** *L Graham, A Halbritter, F Frassinelli* -- Open science lab on writing accessible and reproducible code|`r ilink("video", "https://www.youtube.com/watch?v=fSx71dX88qk&t=1939s", lvl=1)`|
|**A guide to reproducible code in ecology and evolution** *British Ecological Society* -- Basic tools and information for more reproducible code|`r ilink("book", "https://www.britishecologicalsociety.org/wp-content/uploads/2017/12/guide-to-reproducible-code.pdf", lvl=1)`|

*For links on tidyverse, to help code reproducibility, see section Data Manipulation in Basics section.*


### R Markdown & bookdown

| Name                                      | Links |
|-------------------------------------------|-------|
|**Using R Markdown in RStudio** *R Peng* -- A quick demo on R markdown in RStudio|`r ilink("video", "https://www.youtube.com/watch?v=DNS7i2m4sB0", lvl=1)`|
|**Getting started with R Markdown** *G Grolemund & RStudio* -- A detailed webinar on using R Markdown|`r ilink("video", "https://www.rstudio.com/resources/webinars/getting-started-with-r-markdown/", lvl=1)`|
|**R Markdown: The Definitive Guide** *Y Xie, J J Allaire, G Grolemund* -- A complete and introducing reference book to use R Markdown|`r ilink("tuto", "https://bookdown.org/yihui/rmarkdown/")`|
|**R Markdown Cookbook** *Y Xie, C Dervieux, E Riederer* -- A practical reference book for R Markdown|`r ilink("tuto", "https://bookdown.org/yihui/rmarkdown-cookbook/", lvl=2)`|
|**bookdown: Authoring Books and Technical Documents with R Markdown** *Y Xie* -- A complete reference book for R bookdown|`r ilink("tuto", "https://bookdown.org/yihui/bookdown/", lvl=3)`|
|**Tables generator** -- Create a markdown table|`r ilink("site", "https://www.tablesgenerator.com/markdown_tables")`|


### Git & GitHub

| Name                                      | Links |
|-------------------------------------------|-------|
|**Happy Git and GitHub for the useR** -- Learn how to start and integrate git into your daily work with R and Markdown|`r ilink("tuto", "https://happygitwithr.com/index.html", lvl=1)`|
|**Github Docs** -- Official documentation |`r ilink("site", "https://docs.github.com/en")`|


## Ethics

| Name                                      | Links |
|-------------------------------------------|-------|
|**ASA Statement on Statistical Significance and P-Values** *RL Wasserstein & American Statistical Association* -- Six principles underlying the proper use and interpretation of the p-value|`r ilink("article", "https://amstat.tandfonline.com/doi/full/10.1080/00031305.2016.1154108#.Yrn-02ApCqf")`|
|**Ethical Guidelines for Statistical Practice** -- Valuable advice for anyone who engage in statistical practice|`r ilink("site", "https://www.amstat.org/your-career/ethical-guidelines-for-statistical-practice")`|
|**Ten simple rules for good research practice** *S Schwab* -- Good research practices for planning, execution, and reporting of research|`r ilink("article", "https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010139", lvl=1)`|


## Open science

| Name                                      | Links |
|-------------------------------------------|-------|
|**SORTEE** *Society for Open, Reliable, and Transparent Ecology and Evolutionary biology*|`r ilink("site", "https://www.sortee.org/")`|
|**The TOP Guidelines** *Center for Open Science - OSF*|`r ilink("site", "https://www.cos.io/initiatives/top-guidelines")``r ilink("article", "https://osf.io/ud578")`|



