---
title: "Mathematics"
description: |
  Resources on mathematical concepts useful for ecological statistics
        
  maintained by : **Frederic Barraquand** [Click [here to contribute](forms.html)]{style="float:right"}

date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```
###### **Icon Legend**:
**Type**:
full course `r ilink("course", "https:/xcelab.net/rm/statistical-rethinking/")`
video `r ilink("video", "https:/xcelab.net/rm/statistical-rethinking/")`
exo `r ilink("exo", "https:/xcelab.net/rm/statistical-rethinking/")`
open book, tutorial, manual `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/")`
book (not free) `r ilink("book", "https:/xcelab.net/rm/statistical-rethinking/")`
article`r ilink("article", "https:/xcelab.net/rm/statistical-rethinking/")`
website`r ilink("site", "https:/xcelab.net/rm/statistical-rethinking/")`

**level**: begin `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=1)` intermediate `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=2)` advanced `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=3)`

## Calculus

| Name                                      | Links |
|-------------------------------------------|-------|
|**Learning Centennial College** *M Cheung* -- Definitions of useful words|`r ilink("tuto", "https://libraryguides.centennialcollege.ca/c.php?g=717032&p=5115303", lvl=1)`|
|**Derivatives of Common Functions** -- Cheatsheet|`r ilink("tuto", "http://hyperphysics.phy-astr.gsu.edu/hbase/Math/derfunc.html")`|


## Probability

| Name                                      | Links |
|-------------------------------------------|-------|
|**Probability** *S Jadhav* -- Probability theory & description of main distributions, not really ecologist friendly...|`r ilink("course", "https://www.youtube.com/playlist?list=PLcBNhzAt-dF8oas8Z3Post71VF2_Khk2w", lvl=2)`|


## Algebra

| Name                                      | Links |
|-------------------------------------------|-------|
|**Learning Centennial College** *M Cheung* -- Definitions of useful words in linear algebra|`r ilink("tuto", "https://libraryguides.centennialcollege.ca/c.php?g=717345&p=5119504", lvl=1)`|



## Teaching Mathematics in Ecology
| Name                                      | Links |
|-------------------------------------------|-------|
|**What math should ecologists teach?** *B McGill* -- Opinion in a blog, 2014 |`r ilink("site", "https://dynamicecology.wordpress.com/2014/10/20/what-math-should-ecologists-teach/")`|
|**Lack of quantitative training among early-career ecologists: a survey of the problem and potential solutions** *F Barraquand et al.* 2014 |`r ilink("article", "https://peerj.com/articles/285/")`|
|**Writing mathematical ecology: A guide for authors and readers** *L G Shoemaker et al* 2021 |`r ilink("article", "https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.3701")`|
|**Mathematical Ecology: A Century of Progress, and Challenges for the Next Century** *S Levin* -- a lecture in 2017|`r ilink("video", "https://www.youtube.com/watch?v=m6F6MRrDtrQ")`|

