---
title: "Community Analysis"
description: |
  Resources for community analyses
        
  maintained by : *Volunteer Wanted* [Click [here to contribute](forms.html)]{style="float:right"}

date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))

```
###### **Icon Legend**:
**Type**:
full course `r ilink("course", "https:/xcelab.net/rm/statistical-rethinking/")`
video `r ilink("video", "https:/xcelab.net/rm/statistical-rethinking/")`
exo `r ilink("exo", "https:/xcelab.net/rm/statistical-rethinking/")`
open book, tutorial, manual `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/")`
book (not free) `r ilink("book", "https:/xcelab.net/rm/statistical-rethinking/")`
article`r ilink("article", "https:/xcelab.net/rm/statistical-rethinking/")`
website`r ilink("site", "https:/xcelab.net/rm/statistical-rethinking/")`

**level**: begin `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=1)` intermediate `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=2)` advanced `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=3)`

## Overview
| Name                                      | Links |
|-------------------------------------------|-------|
|**Analysis of community ecology data in R** *D Zelený* -- A wiki giving an introductory overview of relevant theory, real community datasets and example R scripts|`r ilink("tuto", "https://www.davidzeleny.net/anadat-r/doku.php/en:start", lvl=1)`|
|**Numerical Ecology** *P Legendre, L Legendre* -- Reference textbook   | `r ilink("book", "https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0")` |
|**Numerical Ecology with R** *D Borcard, F Gillet, P Legendre* -- Exploration of the methods by means of applied and extensively commented examples|  `r ilink("book", "https://link.springer.com/book/10.1007/978-1-4419-7976-6")` |

## Hierarchical Models

## Vegan
A R package for community analysis

| Name                                      | Links |
|-------------------------------------------|-------|
|**Introduction to multivariate data analysis using vegan** *G Simpson* --  a practical introduction to some of the most useful functions in vegan|`r ilink("course", "https://github.com/gavinsimpson/intro-vegan-webinar-july-2020", lvl=1)``r ilink("video", "https://www.youtube.com/watch?v=tVnnG7mFeqA",lvl=1)`|
|**Multivariate Analysis of Ecological Communities in R: vegan tutorial** *J. Oksanen* -- demostrates the use of ordination methods in Rpackage vegan, assumes familiarity both with R and with community ordination |`r ilink("tuto", "https://www.mooreecology.com/uploads/2/4/2/1/24213970/vegantutor.pdf", lvl=2)`|
|**A Vegan Tutorial** *P Clark* -- Quick introduction to useful functions  |`r ilink("tuto", "https://peat-clark.github.io/BIO381/veganTutorial.html", lvl=2)`|
|**Advanced community data analysis using the vegan package in R** *G Simpson N Zimmerman* -- a follow-up to the "Introduction to vegan" session teaching when and how to use multivariate methods including constrained ordination as well as between-group tests|`r ilink("course", "https://github.com/gavinsimpson/esa-advanced-vegan",lvl=2)``r ilink("video", "https://www.youtube.com/watch?v=PR1B_JkO49s", lvl=2)`|
|**Vegan cheat sheet** *A Bui* -- an introductory workshop to useful functions in vegan|`r ilink("tuto", "https://rpubs.com/an-bui/vegan-cheat-sheet")`|



