---
title: "Population dynamics"
description: |
  Resource to model population dynamics
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))

```
###### **Icon Legend**:
**Type**:
full course `r ilink("course", "https:/xcelab.net/rm/statistical-rethinking/")`
video `r ilink("video", "https:/xcelab.net/rm/statistical-rethinking/")`
exo `r ilink("exo", "https:/xcelab.net/rm/statistical-rethinking/")`
open book, tutorial, manual `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/")`
book (not free) `r ilink("book", "https:/xcelab.net/rm/statistical-rethinking/")`
article`r ilink("article", "https:/xcelab.net/rm/statistical-rethinking/")`
website`r ilink("site", "https:/xcelab.net/rm/statistical-rethinking/")`

**level**: begin `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=1)` intermediate `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=2)` advanced `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=3)`



## Overview

| Name                                      | Links |
|-------------------------------------------|-------|
|** ** * * -- |`r ilink("tuto", "")`|



## Equilibrium
## Stochastic
## Transient
## Density-Dependent

## Integral Projection Models
## Integrated Population Models
## Individual Based Models

| Name                                      | Links |
|-------------------------------------------|-------|
|**Individual-based modeling with NetLogoR** *S Bauduin, O Gimenez, O Grente, N Santostasi* -- A 2 Day workshop giving an introduction to individual based models |`r ilink("course", "https://sarahbauduin.github.io/formation_IBM_NetLogoR/", lvl=1)`|

## Social Species

## DEB

## Epidemio
