---
title: "Demography"
description: |
  Resources to model survival, reproduction and growth
        
  maintained by : **Sarah Cubaynes** [Click [here to contribute](forms.html)]{style="float:right"}

date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```
###### **Icon Legend**:
**Type**:
full course `r ilink("course", "https:/xcelab.net/rm/statistical-rethinking/")`
video `r ilink("video", "https:/xcelab.net/rm/statistical-rethinking/")`
exo `r ilink("exo", "https:/xcelab.net/rm/statistical-rethinking/")`
open book, tutorial, manual `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/")`
book (not free) `r ilink("book", "https:/xcelab.net/rm/statistical-rethinking/")`
article`r ilink("article", "https:/xcelab.net/rm/statistical-rethinking/")`
website`r ilink("site", "https:/xcelab.net/rm/statistical-rethinking/")`

**level**: begin `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=1)` intermediate `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=2)` advanced `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=3)`

## Survival

### CMR

| Name                                      | Links |
|-------------------------------------------|-------|
|**Bayesian capture-recapture inference with hidden Markov models** *O Gimenez, C R Nater, S Cubaynes, P de Valpine, M Quéroué* -- A two-day workshop with R and Nimble to learn about how to infer demographic parameters (e.g. survival, dispersal)|`r ilink("course", "https://oliviergimenez.github.io/bayesian-cr-workshop/", lvl=1)`|

## Reproduction

## Growth

