---
title: "Spatial Analysis"
description: |
  Resources for spatial & occupancy analysis
      
  maintained by : *Volunteer Wanted* [Click [here to contribute](forms.html)]{style="float:right"}
  
date: "`r Sys.Date()`"
output: distill::distill_article
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```
###### **Icon Legend**:
**Type**:
course `r ilink("course", "")`
video `r ilink("video", "")`
exo `r ilink("exo", "")`
open book `r ilink("tuto", "")`
book `r ilink("book", "")`
article `r ilink("article", "")`
git repo `r ilink("github", "")`
website `r ilink("site", "")`

**level**: 
begin `r ilink("tuto", "", lvl=1)` intermediate `r ilink("tuto", "", lvl=2)` advanced `r ilink("tuto", "", lvl=3)`



## GIS & Data
| Name                                      | Links |
|-------------------------------------------|-------|
|**Introduction to GIS and mapping in R using the sf package** *O. Gimenez* -- Helpful slides to start mapping in R|`r ilink("course", "https://github.com/oliviergimenez/intro_spatialR#introduction-to-gis-and-mapping-in-r-using-the-sf-package", lvl=1)`|
|**Data wrangling for spatial analysis** *C J Brown, D Schoeman, A J Richardson, B Venables* -- Introduction to spatial analysis with sf |`r ilink("tuto", "https://www.seascapemodels.org/Advanced-spatial-analysis-2021/Advanced-spatial-analysis-2021.html", lvl=1)`|



## Distribution and Abundance

| Name                                      | Links |
|-------------------------------------------|-------|
|**Distance sampling course** *CREEM, University of St Andrews* -- Introduction to distance sampling concepts, survey design, field methods and data analysis|`r ilink("course", "http://workshops.distancesampling.org/online-course/", lvl=1)`|
|**Current approaches to species distribution modelling with R** *C. Brown* Introduction to build, run and visualize species distribution models|`r ilink("tuto", "https://www.seascapemodels.org/SDM-fish-course-notes/", lvl=1)`|


### INLA

| Name                                      | Links |
|-------------------------------------------|-------|
|**Spatial regression in R: INLA** *L Hertzog* -- Spatial regression with INLA package|`r ilink("site", "https://datascienceplus.com/spatial-regression-in-r-part-2-inla", lvl=2)`|
|**The R-INLA project** *H Rue* -- Latent-models with INLA package|`r ilink("tuto", "https://sites.google.com/a/r-inla.org/www/models/latent-models", lvl=2)`|


## Habitat Selection
## Movement
