---
title: "Quantitative Genetics"
description: |
  Resources to apply quantitative genetics
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```
###### **Icon Legend**:
**Type**:
full course `r ilink("course", "https:/xcelab.net/rm/statistical-rethinking/")`
video `r ilink("video", "https:/xcelab.net/rm/statistical-rethinking/")`
exo `r ilink("exo", "https:/xcelab.net/rm/statistical-rethinking/")`
open book, tutorial, manual `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/")`
book (not free) `r ilink("book", "https:/xcelab.net/rm/statistical-rethinking/")`
article`r ilink("article", "https:/xcelab.net/rm/statistical-rethinking/")`
website`r ilink("site", "https:/xcelab.net/rm/statistical-rethinking/")`

**level**: begin `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=1)` intermediate `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=2)` advanced `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=3)`

## Theory in quantitative genetics

| Name                                      | Links |
|-------------------------------------------|-------|
|**Quantitative genetics in the wild** *A. Charmantier, D. Garant & L. EB Kruuk*, 2014 -- A very nice and approachable collection of questions tackled by evolutionary quantitative genetics to study wild populations|`r ilink("book", "https://oxford.universitypressscholarship.com/view/10.1093/acprof:oso/9780199674237.001.0001/acprof-9780199674237", lvl=1)`|
|**Quantitative Genetics** *B. Walsh*, 2016 -- A series of online videos of lectures on evolutionary quantitative genetics, tackling the bases, selection, QTL mapping and many other topics |`r ilink("video", "https://youtube.com/playlist?list=PLtRJ1Uje1ST4aPn6QRQel0rKj1yd_X2RS", lvl=1)`|
|**Genetics and analysis of quantitative traits** *M. Lynch & B. Walsh*, 1998 -- A thorough and in-depth textbook introducing the main concepts of quantitative genetics|`r ilink("book", "https://global.oup.com/ushe/product/genetics-and-analysis-of-quantitative-traits-9780878934812", lvl=2)`|
|**Evolution and selection of quantitative traits** *B. Walsh & M. Lynch*, 2018 -- A more recent update, and extremely thorough textbook on the evolutionary aspects of quantitative genetics |`r ilink("book", "https://oxford.universitypressscholarship.com/view/10.1093/oso/9780198830870.001.0001/oso-9780198830870", lvl=3)`|


## Statistical models

| Name                                      | Links |
|-------------------------------------------|-------|
|**Estimation of a biological trait heritability using the animal model and MCMCglmm** *P. de Villemereuil*, 2021 -- A hands-on tutorial on performing quantitative genetics using a Bayesian method|`r ilink("tuto", "https://devillemereuil.legtux.org/downloads/#h2tutorial", lvl=1)`|
|**Quantitative genetics using the sommer package** *Giovanny Covarrubias-Pazaran*, 2022 -- A guide on how to use the sommer package to perform quantitative genetics |`r ilink("tuto", "https://cran.r-project.org/web/packages/sommer/vignettes/v3.sommer.qg.pdf", lvl=2)`|
|**Wild animal model wiki** *M. Clements, M. Morrissey, A. Wilson, E. Postma, D. Nussey & A. Husby*, 2011 -- A wiki on diverse packages to implement quantitative genetics models. The website is not maintained and contains a few errors, but contains useful "starter code" for some packages.|`r ilink("site", "http://wildanimalmodels.org/tiki-index.php", lvl=1)`|

