---
title: "Mixed Models"
description: |
  Hierarchic models, Generalized and linear mixed models.
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```

To be contacted? Hadfield, Crespin, 



##General

| Name                                      | Links |
|-------------------------------------------|-------|
|Michael Clark site|A series of open course in bayesian analysis, modeling and SEM  |`r ilink("site", "https://m-clark.github.io/documents.html")`|
|Beyond Multiple Linear Regression|Paul Roback and Julie Legler, Applied Generalized Linear Models and Multilevel Models in R |`r ilink("tuto", "https://bookdown.org/roback/bookdown-BeyondMLR/")`|
|  |  |`r ilink("site", " ")`|

|Statistics for ecologists | O. Gimenez: Distibutions, likelihoods, Hypothesis testing, Multimodel inference, Bayesian , GLM, GLMM, GAM|`r ilink("course", "https://github.com/oliviergimenez/statistics-for-ecologists-Master-courses")` `r ilink("video", "")``r ilink("exo", "")`|
|Statistical Thinking for the 21st Century|Russell A. Poldrack|`r ilink("site", "https://statsthinking21.github.io/statsthinking21-core-site/index.html")`|
|  |  |`r ilink("site", " ")`|


##Mixed models

| Name                                      | Links |
|-------------------------------------------|-------|
|Introduction to mixed models |Helen Brown,Senior Statistician, at The Roslin Institute, March 2016.|`r ilink("video", "https://www.youtube.com/playlist?list=PLbyRmcun-giuz5hW11nD64zeiJZSDV4aD")`|
|  |  |`r ilink("site", " ")`|

## Generalized linear mixed models


| Name                                      | Links |
|-------------------------------------------|-------|
|GLMM for ecologists and evolutionary biologists |start with B.Bolker and others|`r ilink("tuto", "http://glmm.wikidot.com/start")`|
|GLMM FAQ|B.Bolker and others|`r ilink("tuto", "https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html")`|
|Rpubs B. Bolker|A list of publications on practical use of GLMM|`r ilink("site", "https://rpubs.com/bbolker")`|
|Generalized linear mixed models: a practical guide for ecology and evolution|B.Bolker and others|`r ilink("article", "https://www.cell.com/trends/ecology-evolution/fulltext/S0169-5347(09)00019-6?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0169534709000196%3Fshowall%3Dtrue")`|
|How to Make Models Add Up — A Primer on GLMMs|R.O'Hara|`r ilink("article", "https://bioone.org/journals/annales-zoologici-fennici/volume-46/issue-2/086.046.0205/How-to-Make-Models-Add-Up--A-Primer-on/10.5735/086.046.0205.short")`|
|GLMM course|S. Anderson and other resources|`r ilink("tuto", "https://github.com/seananderson/glmm-course")`|

Green, P., and C. J. MacLeod. 2016. SIMR: an R package for power analysis of generalized linear mixed models by simulation. Methods in Ecology and Evolution 7:493–498.

Gelman, A., and J. Carlin. 2014. Beyond Power Calculations: Assessing Type S (Sign) and Type M (Magnitude) Errors. Perspectives on Psychological Science 9:641–651.

###p-value

###R2


## GAMM

| Name                                      | Links |
|-------------------------------------------|-------|
|Introduction to Generalized Additive Models with R and mgcv|Gavin Simpson|`r ilink("video", "https://www.youtube.com/watch?v=sgw4cu8hrZM")``r ilink("github", "https://github.com/gavinsimpson/gams-yorku-canada-150")`|
|mgcv course  |G Simpson, N Ross  |`r ilink("site", "https://noamross.github.io/mgcv-esa-2018/")`|
|  |  |`r ilink("site", " ")`|


## Structural Equation Modeling
| Name                                      | Links |
|-------------------------------------------|-------|
|An Introduction to Structural Equation Modeling|Jon Lefcheck|`r ilink("tuto", "https://jslefche.github.io/sem_book/")`|



