---
title: "Multivariate Analysis"
description: |
  Resources to learn and develop multivariate analyses
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```
###### **Icon Legend**:
**Type**:
full course `r ilink("course", "https:/xcelab.net/rm/statistical-rethinking/")`
video `r ilink("video", "https:/xcelab.net/rm/statistical-rethinking/")`
exo `r ilink("exo", "https:/xcelab.net/rm/statistical-rethinking/")`
open book, tutorial, manual `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/")`
book (not free) `r ilink("book", "https:/xcelab.net/rm/statistical-rethinking/")`
article`r ilink("article", "https:/xcelab.net/rm/statistical-rethinking/")`
website`r ilink("site", "https:/xcelab.net/rm/statistical-rethinking/")`

**level**: begin `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=1)` intermediate `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=2)` advanced `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=3)`


## Overview


| Name                                      | Links |
|-------------------------------------------|-------|
|**Multivariate Analysis** *S. Jadhav* A list of videos introducing r, multivariate analysis, PCA and clustering|`r ilink("video", "https://www.youtube.com/playlist?list=PLcBNhzAt-dF_7oBNpuSDsVAur0s7MwM2v", lvl=1)`|
|**Exploratory Multivariate Data Analysis** *F Husson, J Pagès, M Houée-Bigot* -- a MOOC including PCA, CA, MCA and clustering|`r ilink("course", "https://www.fun-mooc.fr/en/courses/exploratory-multivariate-data-analysis/", lvl=1)`|
|**Gusta Me** -- a website describing range of analysis techniques used in microbial ecology including data preparation, ordination and clustering methods |`r ilink("tuto", "https://sites.google.com/site/mb3gustame/", lvl=1)``r ilink("github", "https://github.com/pbuttigieg/masame", lvl=1)`|
|**Applied Multivariate Statistical Analysis** *Penn State College* -- a full course  examining a variety of statistical methods for multivariate data, including multivariate extensions of t-tests and analysis of variance, dimension reduction techniques such as principal component analysis, factor analysis, canonical correlation analysis, and classification and clustering methods.|`r ilink("tuto", "https://online.stat.psu.edu/stat505/", lvl=2)`|
|**Multivariate Analysis** *S Dray* -- Slides from a Master course including PCA, correspondance analysis & two-table analysis|`r ilink("course", "https://github.com/sdray/INSAcourse", lvl=2)`|




## Ordination Methods
| Name                                      | Links |
|-------------------------------------------|-------|
|**Ordination Methods for Ecologists** *M. Palmer* -- A full presentation of theory and main ordination methods|`r ilink("site", "http://ordination.okstate.edu/", lvl=2)`|

related links: <http://ordination.okstate.edu/otherlinks.html>

## Clustering
