---
title: "Bayesian Approach"
description: |
  Resources for Bayesian modeling
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```
###### **Icon Legend**:
**Type**:
full course `r ilink("course", "https:/xcelab.net/rm/statistical-rethinking/")`
video `r ilink("video", "https:/xcelab.net/rm/statistical-rethinking/")`
exo `r ilink("exo", "https:/xcelab.net/rm/statistical-rethinking/")`
open book, tutorial, manual `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/")`
book (not free) `r ilink("book", "https:/xcelab.net/rm/statistical-rethinking/")`
article`r ilink("article", "https:/xcelab.net/rm/statistical-rethinking/")`
website`r ilink("site", "https:/xcelab.net/rm/statistical-rethinking/")`

**level**: begin `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=1)` intermediate `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=2)` advanced `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=3)`


## Overview

| Name                                      | Links |
|-------------------------------------------|-------|
|**Bayesian statistics with R** *O. Gimenez* -- A clear introduction to Bayesian analysis using R and jags| `r ilink("course", "https://oliviergimenez.github.io/bayesian-stats-with-R/", lvl=1)`|
|**Statistical Rethinking** *R McElreath* -- A complete course about Bayesian inference and regression, including covariance structure, using stan |`r ilink("course", "https://github.com/rmcelreath/statrethinking_winter2019", lvl=1)` `r ilink("book", "https:/xcelab.net/rm/statistical-rethinking/")`|
|**Bayesian Modeling for Socio-Environmental Data** *T Hobbs, M Collins, C Che-Castaldo* -- A course with r and jags providing an understanding to Bayesian methods, statistical concepts and methodology|`r ilink("course", "https://cchecastaldo.github.io/BayesianShortCourse/index.html", lvl=1)`|
|**Bayesian statistics course** *F. Barraquand* -- A full Master course to learn Baysian statistics including MCMC, Anova, GLMM, non-linear models, occupancy models and model selection|`r ilink("course", "https://github.com/fbarraquand/Bayesian_statistics_course", lvl=2)`|
|**BiogecoBayes** -- A collection of useful workshops created by a group of researchers & students who want to progress together in their learning|`r ilink("tuto", "https://github.com/JulietteArchambeau/BiogecoBayes", lvl=1)`|
|**Bayesian Models: A Statistical Primer for Ecologists** *T Hobbs, M Hooten* -- Presents the mathematical and statistical foundations of Bayesian modeling in language accessible to non-statisticians|`r ilink("book", "https://www.amazon.com/Bayesian-Models-Statistical-Primer-Ecologists/dp/0691159289", lvl=1)`|
|**Learning Bayesian Statistics** -- a podcast channel presenting scientists, their approach and thinking|`r ilink("site", "https://www.learnbayesstats.com/", lvl=2)`|


## Priors

| Name                                      | Links |
|-------------------------------------------|-------|

## MCMC

| Name                                      | Links |
|-------------------------------------------|-------|
|**The Markov-chain Monte Carlo Interactive Gallery** -- view algorithms|`r ilink("site", "https://chi-feng.github.io/mcmc-demo/")`|


## Convergence and Identifiability

| Name                                      | Links |
|-------------------------------------------|-------|




## Packages and software
### JAGS
### Stan

| Name                                      | Links |
|-------------------------------------------|-------|
|**Become a Bayesian with R & Stan** *M Clark* -- an introduction to the probabilistic programming language Stan|`r ilink("tuto", "http://m-clark.github.io/workshops/bayesian/index.html#home", lvl=1)`|
|**Stan for Ecology** -- location for all types of works in ecology that use the software Stan for Bayesian inference|`r ilink("site", "https://stanecology.github.io/")`|
|**Stan User Guide** *Stan Development Team* -- |`r ilink("tuto", "https://mc-stan.org/docs/2_21/stan-users-guide/index.html")`|


### Nimble

| Name                                      | Links |
|-------------------------------------------|-------|
|**nimble-training** *C Paciorek, D Turek, P de Valpine* -- several workshops to learn programming with nimble|`r ilink("github", "https://github.com/nimble-training")`|
|**nimble manual** *NIMBLE Development Team* -- official & useful manual |`r ilink("tuto", "https://r-nimble.org/manuals/NimbleUserManual.pdf")`|
|**nimble cheatsheet** |`r ilink("tuto", "https://r-nimble.org/cheatsheets/NimbleCheatSheet.pdf")`|
|**nimble** *NIMBLE Development Team* -- nimble website, download, find examples and documentation |`r ilink("site", "https://r-nimble.org/")`|
