---
title: "Links"
description: |
  A list of untidy links
date: "`r Sys.Date()`"
output: distill::distill_article
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
```
###### **Icon Legend**:
**Type**:
full course `r ilink("course", "https:/xcelab.net/rm/statistical-rethinking/")`
video `r ilink("video", "https:/xcelab.net/rm/statistical-rethinking/")`
exo `r ilink("exo", "https:/xcelab.net/rm/statistical-rethinking/")`
open book, tutorial, manual `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/")`
book (not free) `r ilink("book", "https:/xcelab.net/rm/statistical-rethinking/")`
article`r ilink("article", "https:/xcelab.net/rm/statistical-rethinking/")`
website`r ilink("site", "https:/xcelab.net/rm/statistical-rethinking/")`

**level**: begin `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=1)` intermediate `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=2)` advanced `r ilink("tuto", "https:/xcelab.net/rm/statistical-rethinking/", lvl=3)`

| Name                                      | Links |
|-------------------------------------------|-------|
|**Cross-Validated** -- The statistical forum|`r ilink("site", "https://stats.stackexchange.com/")`|
|**Ourcodingclub** -- Many different tutorial made by a group of student and researcher from the University of Edinburgh |`r ilink("site", "https://ourcodingclub.github.io/tutorials.html")`|
|**Ecological Applications in R** -- a youtube channel creating for the Covid |`r ilink("video", "https://www.youtube.com/channel/UCLBUT7zCp6wW_BXvc8094dA")`|
|**Conservation hackers** -- forum, blog and courses for conservation scientists  |`r ilink("site", "https://www.conservationhackers.org/")``r ilink("video", "https://www.youtube.com/channel/UCSH4ctGD-waPSI_4w6PlTBg")`|
|**R4DS** -- a community of R learners at all skill levels working together to improve their skills  |`r ilink("video", "https://www.youtube.com/c/R4DSOnlineLearningCommunity/featured")`|
|**Discdown** -- regrouping courses such as Data Analytic, programming in R and Flexible Regressions  |`r ilink("site", "https://discdown.org/index.php")`|

